security:
  basic:
    enabled: false
spring:
  thymeleaf:
    cache: false
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    url: jdbc:mysql://localhost:3306/reply_board?autoReconnect=true&useUnicode=false&characterEncoding=utf8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: tmddbs0723!@1!
  jpa:
    show-sql: false
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        